// Scene keys, asset keys and the single URL the game boots from. Scenes never hard-code asset URLs: every file is
// listed in the Phaser asset pack (public/assets/town/asset-pack.json) and referenced by key.
//
// No Phaser import: safe to import from anywhere.

export const ASSET_PACK_URL = "/assets/town/asset-pack.json";
/** the same .tmj the pack lists; the HUD reads location labels / owners from it */
export const TOWN_MAP_URL = "/assets/town/polis-town.tmj";

export const SCENES = {
  boot: "Boot",
  preloader: "Preloader",
  town: "Town",
  /** persistent background scene that owns the AudioManager and the (non-blocking) audio loader */
  audio: "Audio"
} as const;

export const KEYS = {
  /** the asset pack manifest as a JSON cache entry (loaded by BootScene) */
  manifest: "asset-pack",
  /** pack file key passed to load.pack */
  pack: "town-pack",
  tileset: "town-tileset",
  map: "town-map",
  /** name of the tileset inside the .tmj */
  tilesetName: "polis-tileset",
  /** generated by BootScene for the loading bar */
  barFrame: "bar-frame",
  barFill: "bar-fill",
  /** 9-slice frame of the speech bubbles (public/assets/ui/frame-paper-s.png, listed in the pack's `hud` section) */
  bubbleFrame: "hud-paper-s"
} as const;

/** The sections of the asset pack the Preloader waits for. Audio sections are NOT in this list: they are loaded in
 *  the background by the AudioScene after the town is on screen, so audio decoding can never hold the game back. */
export const BLOCKING_PACK_SECTIONS = ["town", "ui", "hud"] as const;
/** audio sections, loaded in this order by the AudioScene (sfx + title music first, the 70 s loops afterwards) */
export const AUDIO_PACK_SECTIONS = ["audio-core", "audio-bgm"] as const;

/** tile layer names of the map, bottom to top (collision is read by tiled.ts, never drawn) */
export const MAP_LAYERS = ["ground", "paths", "water", "deco", "buildings"] as const;
export const MAP_ABOVE_LAYER = "above";

/** Phaser texture key of an emote icon */
export const emoteTexture = (emote: string): string => `emote-${emote}`;

/** render depths (residents sort by their feet y between DEPTH.residents and DEPTH.above) */
export const DEPTH = {
  ground: 0,
  paths: 1,
  water: 2,
  deco: 3,
  buildings: 4,
  residents: 10,
  above: 5000,
  hover: 8000,
  grade: 15000,
  ui: 20000
} as const;

export const BG_COLOR = "#0b1020";

// ───────────────────────────── typography ─────────────────────────────

/** The one pixel font of the whole game (OFL, full Simplified Chinese; @fontsource/fusion-pixel-12px-proportional-sc,
 *  imported once in app/layout.tsx). It is drawn on a 12 px grid: always render it at 12 / 24 / 36 px so every
 *  glyph pixel lands on a whole screen pixel. */
export const PIXEL_FONT_NAME = "Fusion Pixel 12px Proportional SC";
export const PIXEL_FONT = `"${PIXEL_FONT_NAME}","PingFang SC","Noto Sans CJK SC","Noto Sans SC","Microsoft YaHei",sans-serif`;

/** Resolves once the pixel font is usable (or after a short timeout / on failure, so a missing font can never hold
 *  the game back). Phaser caches text metrics when a Text object is created, so Boot waits for this before the
 *  Preloader and the Town create any text. */
export function ensurePixelFont(timeoutMs = 4000): Promise<void> {
  if (typeof document === "undefined" || !document.fonts) return Promise.resolve();
  const load = document.fonts.load(`12px "${PIXEL_FONT_NAME}"`, "POLIS 小镇守护灵 0123456789").then(
    () => undefined,
    () => undefined
  );
  const timeout = new Promise<void>((resolve) => window.setTimeout(resolve, timeoutMs));
  return Promise.race([load, timeout]);
}

// ───────────────────────────── audio vocabulary ─────────────────────────────

/** background music beds: the title screen, daytime 06:00–19:59, and the rest of the night */
export type BgmMode = "title" | "day" | "night";
export const BGM_KEY: Record<BgmMode, string> = { title: "bgm-title", day: "bgm-day", night: "bgm-night" };

export type SfxName = "click" | "confirm" | "moment" | "postcard" | "imprint" | "coin" | "voice" | "error";
export const SFX_NAMES: SfxName[] = ["click", "confirm", "moment", "postcard", "imprint", "coin", "voice", "error"];
export const sfxKey = (name: SfxName): string => `sfx-${name}`;
/** every audio key the asset pack provides */
export const AUDIO_KEYS: string[] = [...Object.values(BGM_KEY), ...SFX_NAMES.map(sfxKey)];

export interface AudioSettings {
  music: boolean;
  /** 0..1 */
  musicVol: number;
  sfx: boolean;
  /** 0..1 */
  sfxVol: number;
}
export const DEFAULT_AUDIO_SETTINGS: AudioSettings = { music: true, musicVol: 0.6, sfx: true, sfxVol: 0.8 };

export interface AudioStatus {
  /** audio cache keys that decoded fine */
  loaded: string[];
  /** keys whose file failed to load / decode */
  failed: string[];
  /** the browser still waits for a user gesture before it lets us play */
  locked: boolean;
  bgm: BgmMode | null;
}
