// Scene keys, asset keys and the single URL the game boots from. Scenes never hard-code asset URLs: every file is
// listed in the Phaser asset pack (public/assets/town/asset-pack.json) and referenced by key.
//
// No Phaser import: safe to import from anywhere.

export const ASSET_PACK_URL = "/assets/town/asset-pack.json";
/** the same .tmj the pack lists; the HUD reads location labels / owners from it */
export const TOWN_MAP_URL = "/assets/town/polis-town.tmj";

export const SCENES = {
  boot: "Boot",
  preloader: "Preloader",
  town: "Town"
} as const;

export const KEYS = {
  /** the asset pack manifest as a JSON cache entry (loaded by BootScene) */
  manifest: "asset-pack",
  /** pack file key passed to load.pack */
  pack: "town-pack",
  tileset: "town-tileset",
  map: "town-map",
  /** name of the tileset inside the .tmj */
  tilesetName: "polis-tileset",
  /** generated by BootScene for the loading bar */
  barFrame: "bar-frame",
  barFill: "bar-fill"
} as const;

/** tile layer names of the map, bottom to top (collision is read by tiled.ts, never drawn) */
export const MAP_LAYERS = ["ground", "paths", "water", "deco", "buildings"] as const;
export const MAP_ABOVE_LAYER = "above";

/** Phaser texture key of an emote icon */
export const emoteTexture = (emote: string): string => `emote-${emote}`;

/** render depths (residents sort by their feet y between DEPTH.residents and DEPTH.above) */
export const DEPTH = {
  ground: 0,
  paths: 1,
  water: 2,
  deco: 3,
  buildings: 4,
  residents: 10,
  above: 5000,
  hover: 8000,
  grade: 15000,
  ui: 20000
} as const;

export const BG_COLOR = "#0b1020";
